{
    "config": {
        "abort": {
            "already_configured": "Der Dienst ist bereits konfiguriert",
            "reauth_successful": "Die erneute Authentifizierung war erfolgreich"
        },
        "error": {
            "cannot_connect": "Verbindung fehlgeschlagen",
            "invalid_auth": "Ung\u00fcltige Authentifizierung",
            "invalid_url": "Ung\u00fcltige URL",
            "unknown": "Unerwarteter Fehler"
        },
        "step": {
            "user": {
                "data": {
                    "url": "URL"
                }
            }
        }
    }
}